// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema

#ifndef GOOGLE_PROTOBUF_INCLUDED_schema
#define GOOGLE_PROTOBUF_INCLUDED_schema

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_schema
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_schema {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_schema;
namespace ipfix {
class FlowRecord;
struct FlowRecordDefaultTypeInternal;
extern FlowRecordDefaultTypeInternal _FlowRecord_default_instance_;
}  // namespace ipfix
PROTOBUF_NAMESPACE_OPEN
template<> ::ipfix::FlowRecord* Arena::CreateMaybeMessage<::ipfix::FlowRecord>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ipfix {

// ===================================================================

class FlowRecord final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ipfix.FlowRecord) */ {
 public:
  inline FlowRecord() : FlowRecord(nullptr) {}
  ~FlowRecord() override;
  explicit PROTOBUF_CONSTEXPR FlowRecord(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FlowRecord(const FlowRecord& from);
  FlowRecord(FlowRecord&& from) noexcept
    : FlowRecord() {
    *this = ::std::move(from);
  }

  inline FlowRecord& operator=(const FlowRecord& from) {
    CopyFrom(from);
    return *this;
  }
  inline FlowRecord& operator=(FlowRecord&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FlowRecord& default_instance() {
    return *internal_default_instance();
  }
  static inline const FlowRecord* internal_default_instance() {
    return reinterpret_cast<const FlowRecord*>(
               &_FlowRecord_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(FlowRecord& a, FlowRecord& b) {
    a.Swap(&b);
  }
  inline void Swap(FlowRecord* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FlowRecord* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FlowRecord* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FlowRecord>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const FlowRecord& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const FlowRecord& from) {
    FlowRecord::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FlowRecord* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ipfix.FlowRecord";
  }
  protected:
  explicit FlowRecord(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSRCIPFieldNumber = 1,
    kDSTIPFieldNumber = 2,
    kDNSQNAMEFieldNumber = 26,
    kTLSSNIFieldNumber = 31,
    kHTTPREQUESTAGENTFieldNumber = 41,
    kHTTPREQUESTHOSTFieldNumber = 42,
    kHTTPREQUESTREFERERFieldNumber = 43,
    kHTTPREQUESTURLFieldNumber = 44,
    kHTTPRESPONSECONTENTTYPEFieldNumber = 45,
    kSRCPORTFieldNumber = 3,
    kDSTPORTFieldNumber = 4,
    kBYTESFieldNumber = 6,
    kBYTESREVFieldNumber = 7,
    kPACKETSFieldNumber = 8,
    kPROTOCOLFieldNumber = 5,
    kTCPFLAGSFieldNumber = 12,
    kPACKETSREVFieldNumber = 9,
    kTIMEFIRSTFieldNumber = 10,
    kTIMELASTFieldNumber = 11,
    kTCPFLAGSREVFieldNumber = 13,
    kTTLFieldNumber = 14,
    kTTLREVFieldNumber = 15,
    kFLOWENDREASONFieldNumber = 16,
    kDNSANSWERSFieldNumber = 20,
    kDNSIDFieldNumber = 21,
    kDNSQTYPEFieldNumber = 22,
    kDNSRRRLENGTHFieldNumber = 23,
    kDNSDOFieldNumber = 24,
    kDNSRCODEFieldNumber = 25,
    kFMETLSSERVERVERSIONFieldNumber = 30,
    kHTTPRESPONSESTATUSCODEFieldNumber = 40,
    kFLOWIDFieldNumber = 50,
    kFLOWCOUNTFieldNumber = 51,
  };
  // bytes SRC_IP = 1;
  void clear_src_ip();
  const std::string& src_ip() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_src_ip(ArgT0&& arg0, ArgT... args);
  std::string* mutable_src_ip();
  PROTOBUF_NODISCARD std::string* release_src_ip();
  void set_allocated_src_ip(std::string* src_ip);
  private:
  const std::string& _internal_src_ip() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_src_ip(const std::string& value);
  std::string* _internal_mutable_src_ip();
  public:

  // bytes DST_IP = 2;
  void clear_dst_ip();
  const std::string& dst_ip() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_dst_ip(ArgT0&& arg0, ArgT... args);
  std::string* mutable_dst_ip();
  PROTOBUF_NODISCARD std::string* release_dst_ip();
  void set_allocated_dst_ip(std::string* dst_ip);
  private:
  const std::string& _internal_dst_ip() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_dst_ip(const std::string& value);
  std::string* _internal_mutable_dst_ip();
  public:

  // bytes DNS_Q_NAME = 26;
  void clear_dns_q_name();
  const std::string& dns_q_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_dns_q_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_dns_q_name();
  PROTOBUF_NODISCARD std::string* release_dns_q_name();
  void set_allocated_dns_q_name(std::string* dns_q_name);
  private:
  const std::string& _internal_dns_q_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_dns_q_name(const std::string& value);
  std::string* _internal_mutable_dns_q_name();
  public:

  // string TLS_SNI = 31;
  void clear_tls_sni();
  const std::string& tls_sni() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_tls_sni(ArgT0&& arg0, ArgT... args);
  std::string* mutable_tls_sni();
  PROTOBUF_NODISCARD std::string* release_tls_sni();
  void set_allocated_tls_sni(std::string* tls_sni);
  private:
  const std::string& _internal_tls_sni() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_tls_sni(const std::string& value);
  std::string* _internal_mutable_tls_sni();
  public:

  // string HTTP_REQUEST_AGENT = 41;
  void clear_http_request_agent();
  const std::string& http_request_agent() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_http_request_agent(ArgT0&& arg0, ArgT... args);
  std::string* mutable_http_request_agent();
  PROTOBUF_NODISCARD std::string* release_http_request_agent();
  void set_allocated_http_request_agent(std::string* http_request_agent);
  private:
  const std::string& _internal_http_request_agent() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_http_request_agent(const std::string& value);
  std::string* _internal_mutable_http_request_agent();
  public:

  // string HTTP_REQUEST_HOST = 42;
  void clear_http_request_host();
  const std::string& http_request_host() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_http_request_host(ArgT0&& arg0, ArgT... args);
  std::string* mutable_http_request_host();
  PROTOBUF_NODISCARD std::string* release_http_request_host();
  void set_allocated_http_request_host(std::string* http_request_host);
  private:
  const std::string& _internal_http_request_host() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_http_request_host(const std::string& value);
  std::string* _internal_mutable_http_request_host();
  public:

  // string HTTP_REQUEST_REFERER = 43;
  void clear_http_request_referer();
  const std::string& http_request_referer() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_http_request_referer(ArgT0&& arg0, ArgT... args);
  std::string* mutable_http_request_referer();
  PROTOBUF_NODISCARD std::string* release_http_request_referer();
  void set_allocated_http_request_referer(std::string* http_request_referer);
  private:
  const std::string& _internal_http_request_referer() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_http_request_referer(const std::string& value);
  std::string* _internal_mutable_http_request_referer();
  public:

  // string HTTP_REQUEST_URL = 44;
  void clear_http_request_url();
  const std::string& http_request_url() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_http_request_url(ArgT0&& arg0, ArgT... args);
  std::string* mutable_http_request_url();
  PROTOBUF_NODISCARD std::string* release_http_request_url();
  void set_allocated_http_request_url(std::string* http_request_url);
  private:
  const std::string& _internal_http_request_url() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_http_request_url(const std::string& value);
  std::string* _internal_mutable_http_request_url();
  public:

  // string HTTP_RESPONSE_CONTENT_TYPE = 45;
  void clear_http_response_content_type();
  const std::string& http_response_content_type() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_http_response_content_type(ArgT0&& arg0, ArgT... args);
  std::string* mutable_http_response_content_type();
  PROTOBUF_NODISCARD std::string* release_http_response_content_type();
  void set_allocated_http_response_content_type(std::string* http_response_content_type);
  private:
  const std::string& _internal_http_response_content_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_http_response_content_type(const std::string& value);
  std::string* _internal_mutable_http_response_content_type();
  public:

  // uint32 SRC_PORT = 3;
  void clear_src_port();
  uint32_t src_port() const;
  void set_src_port(uint32_t value);
  private:
  uint32_t _internal_src_port() const;
  void _internal_set_src_port(uint32_t value);
  public:

  // uint32 DST_PORT = 4;
  void clear_dst_port();
  uint32_t dst_port() const;
  void set_dst_port(uint32_t value);
  private:
  uint32_t _internal_dst_port() const;
  void _internal_set_dst_port(uint32_t value);
  public:

  // fixed64 BYTES = 6;
  void clear_bytes();
  uint64_t bytes() const;
  void set_bytes(uint64_t value);
  private:
  uint64_t _internal_bytes() const;
  void _internal_set_bytes(uint64_t value);
  public:

  // fixed64 BYTES_REV = 7;
  void clear_bytes_rev();
  uint64_t bytes_rev() const;
  void set_bytes_rev(uint64_t value);
  private:
  uint64_t _internal_bytes_rev() const;
  void _internal_set_bytes_rev(uint64_t value);
  public:

  // fixed64 PACKETS = 8;
  void clear_packets();
  uint64_t packets() const;
  void set_packets(uint64_t value);
  private:
  uint64_t _internal_packets() const;
  void _internal_set_packets(uint64_t value);
  public:

  // uint32 PROTOCOL = 5;
  void clear_protocol();
  uint32_t protocol() const;
  void set_protocol(uint32_t value);
  private:
  uint32_t _internal_protocol() const;
  void _internal_set_protocol(uint32_t value);
  public:

  // uint32 TCP_FLAGS = 12;
  void clear_tcp_flags();
  uint32_t tcp_flags() const;
  void set_tcp_flags(uint32_t value);
  private:
  uint32_t _internal_tcp_flags() const;
  void _internal_set_tcp_flags(uint32_t value);
  public:

  // fixed64 PACKETS_REV = 9;
  void clear_packets_rev();
  uint64_t packets_rev() const;
  void set_packets_rev(uint64_t value);
  private:
  uint64_t _internal_packets_rev() const;
  void _internal_set_packets_rev(uint64_t value);
  public:

  // fixed64 TIME_FIRST = 10;
  void clear_time_first();
  uint64_t time_first() const;
  void set_time_first(uint64_t value);
  private:
  uint64_t _internal_time_first() const;
  void _internal_set_time_first(uint64_t value);
  public:

  // fixed64 TIME_LAST = 11;
  void clear_time_last();
  uint64_t time_last() const;
  void set_time_last(uint64_t value);
  private:
  uint64_t _internal_time_last() const;
  void _internal_set_time_last(uint64_t value);
  public:

  // uint32 TCP_FLAGS_REV = 13;
  void clear_tcp_flags_rev();
  uint32_t tcp_flags_rev() const;
  void set_tcp_flags_rev(uint32_t value);
  private:
  uint32_t _internal_tcp_flags_rev() const;
  void _internal_set_tcp_flags_rev(uint32_t value);
  public:

  // uint32 TTL = 14;
  void clear_ttl();
  uint32_t ttl() const;
  void set_ttl(uint32_t value);
  private:
  uint32_t _internal_ttl() const;
  void _internal_set_ttl(uint32_t value);
  public:

  // uint32 TTL_REV = 15;
  void clear_ttl_rev();
  uint32_t ttl_rev() const;
  void set_ttl_rev(uint32_t value);
  private:
  uint32_t _internal_ttl_rev() const;
  void _internal_set_ttl_rev(uint32_t value);
  public:

  // uint32 FLOW_END_REASON = 16;
  void clear_flow_end_reason();
  uint32_t flow_end_reason() const;
  void set_flow_end_reason(uint32_t value);
  private:
  uint32_t _internal_flow_end_reason() const;
  void _internal_set_flow_end_reason(uint32_t value);
  public:

  // uint32 DNS_ANSWERS = 20;
  void clear_dns_answers();
  uint32_t dns_answers() const;
  void set_dns_answers(uint32_t value);
  private:
  uint32_t _internal_dns_answers() const;
  void _internal_set_dns_answers(uint32_t value);
  public:

  // uint32 DNS_ID = 21;
  void clear_dns_id();
  uint32_t dns_id() const;
  void set_dns_id(uint32_t value);
  private:
  uint32_t _internal_dns_id() const;
  void _internal_set_dns_id(uint32_t value);
  public:

  // uint32 DNS_Q_TYPE = 22;
  void clear_dns_q_type();
  uint32_t dns_q_type() const;
  void set_dns_q_type(uint32_t value);
  private:
  uint32_t _internal_dns_q_type() const;
  void _internal_set_dns_q_type(uint32_t value);
  public:

  // uint32 DNS_RR_RLENGTH = 23;
  void clear_dns_rr_rlength();
  uint32_t dns_rr_rlength() const;
  void set_dns_rr_rlength(uint32_t value);
  private:
  uint32_t _internal_dns_rr_rlength() const;
  void _internal_set_dns_rr_rlength(uint32_t value);
  public:

  // uint32 DNS_DO = 24;
  void clear_dns_do();
  uint32_t dns_do() const;
  void set_dns_do(uint32_t value);
  private:
  uint32_t _internal_dns_do() const;
  void _internal_set_dns_do(uint32_t value);
  public:

  // uint32 DNS_RCODE = 25;
  void clear_dns_rcode();
  uint32_t dns_rcode() const;
  void set_dns_rcode(uint32_t value);
  private:
  uint32_t _internal_dns_rcode() const;
  void _internal_set_dns_rcode(uint32_t value);
  public:

  // uint32 FME_TLS_SERVER_VERSION = 30;
  void clear_fme_tls_server_version();
  uint32_t fme_tls_server_version() const;
  void set_fme_tls_server_version(uint32_t value);
  private:
  uint32_t _internal_fme_tls_server_version() const;
  void _internal_set_fme_tls_server_version(uint32_t value);
  public:

  // uint32 HTTP_RESPONSE_STATUS_CODE = 40;
  void clear_http_response_status_code();
  uint32_t http_response_status_code() const;
  void set_http_response_status_code(uint32_t value);
  private:
  uint32_t _internal_http_response_status_code() const;
  void _internal_set_http_response_status_code(uint32_t value);
  public:

  // uint64 FLOW_ID = 50;
  void clear_flow_id();
  uint64_t flow_id() const;
  void set_flow_id(uint64_t value);
  private:
  uint64_t _internal_flow_id() const;
  void _internal_set_flow_id(uint64_t value);
  public:

  // uint64 FLOW_COUNT = 51;
  void clear_flow_count();
  uint64_t flow_count() const;
  void set_flow_count(uint64_t value);
  private:
  uint64_t _internal_flow_count() const;
  void _internal_set_flow_count(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:ipfix.FlowRecord)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr src_ip_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr dst_ip_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr dns_q_name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr tls_sni_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr http_request_agent_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr http_request_host_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr http_request_referer_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr http_request_url_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr http_response_content_type_;
    uint32_t src_port_;
    uint32_t dst_port_;
    uint64_t bytes_;
    uint64_t bytes_rev_;
    uint64_t packets_;
    uint32_t protocol_;
    uint32_t tcp_flags_;
    uint64_t packets_rev_;
    uint64_t time_first_;
    uint64_t time_last_;
    uint32_t tcp_flags_rev_;
    uint32_t ttl_;
    uint32_t ttl_rev_;
    uint32_t flow_end_reason_;
    uint32_t dns_answers_;
    uint32_t dns_id_;
    uint32_t dns_q_type_;
    uint32_t dns_rr_rlength_;
    uint32_t dns_do_;
    uint32_t dns_rcode_;
    uint32_t fme_tls_server_version_;
    uint32_t http_response_status_code_;
    uint64_t flow_id_;
    uint64_t flow_count_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_schema;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FlowRecord

// bytes SRC_IP = 1;
inline void FlowRecord::clear_src_ip() {
  _impl_.src_ip_.ClearToEmpty();
}
inline const std::string& FlowRecord::src_ip() const {
  // @@protoc_insertion_point(field_get:ipfix.FlowRecord.SRC_IP)
  return _internal_src_ip();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FlowRecord::set_src_ip(ArgT0&& arg0, ArgT... args) {
 
 _impl_.src_ip_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ipfix.FlowRecord.SRC_IP)
}
inline std::string* FlowRecord::mutable_src_ip() {
  std::string* _s = _internal_mutable_src_ip();
  // @@protoc_insertion_point(field_mutable:ipfix.FlowRecord.SRC_IP)
  return _s;
}
inline const std::string& FlowRecord::_internal_src_ip() const {
  return _impl_.src_ip_.Get();
}
inline void FlowRecord::_internal_set_src_ip(const std::string& value) {
  
  _impl_.src_ip_.Set(value, GetArenaForAllocation());
}
inline std::string* FlowRecord::_internal_mutable_src_ip() {
  
  return _impl_.src_ip_.Mutable(GetArenaForAllocation());
}
inline std::string* FlowRecord::release_src_ip() {
  // @@protoc_insertion_point(field_release:ipfix.FlowRecord.SRC_IP)
  return _impl_.src_ip_.Release();
}
inline void FlowRecord::set_allocated_src_ip(std::string* src_ip) {
  if (src_ip != nullptr) {
    
  } else {
    
  }
  _impl_.src_ip_.SetAllocated(src_ip, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.src_ip_.IsDefault()) {
    _impl_.src_ip_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ipfix.FlowRecord.SRC_IP)
}

// bytes DST_IP = 2;
inline void FlowRecord::clear_dst_ip() {
  _impl_.dst_ip_.ClearToEmpty();
}
inline const std::string& FlowRecord::dst_ip() const {
  // @@protoc_insertion_point(field_get:ipfix.FlowRecord.DST_IP)
  return _internal_dst_ip();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FlowRecord::set_dst_ip(ArgT0&& arg0, ArgT... args) {
 
 _impl_.dst_ip_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ipfix.FlowRecord.DST_IP)
}
inline std::string* FlowRecord::mutable_dst_ip() {
  std::string* _s = _internal_mutable_dst_ip();
  // @@protoc_insertion_point(field_mutable:ipfix.FlowRecord.DST_IP)
  return _s;
}
inline const std::string& FlowRecord::_internal_dst_ip() const {
  return _impl_.dst_ip_.Get();
}
inline void FlowRecord::_internal_set_dst_ip(const std::string& value) {
  
  _impl_.dst_ip_.Set(value, GetArenaForAllocation());
}
inline std::string* FlowRecord::_internal_mutable_dst_ip() {
  
  return _impl_.dst_ip_.Mutable(GetArenaForAllocation());
}
inline std::string* FlowRecord::release_dst_ip() {
  // @@protoc_insertion_point(field_release:ipfix.FlowRecord.DST_IP)
  return _impl_.dst_ip_.Release();
}
inline void FlowRecord::set_allocated_dst_ip(std::string* dst_ip) {
  if (dst_ip != nullptr) {
    
  } else {
    
  }
  _impl_.dst_ip_.SetAllocated(dst_ip, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.dst_ip_.IsDefault()) {
    _impl_.dst_ip_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ipfix.FlowRecord.DST_IP)
}

// uint32 SRC_PORT = 3;
inline void FlowRecord::clear_src_port() {
  _impl_.src_port_ = 0u;
}
inline uint32_t FlowRecord::_internal_src_port() const {
  return _impl_.src_port_;
}
inline uint32_t FlowRecord::src_port() const {
  // @@protoc_insertion_point(field_get:ipfix.FlowRecord.SRC_PORT)
  return _internal_src_port();
}
inline void FlowRecord::_internal_set_src_port(uint32_t value) {
  
  _impl_.src_port_ = value;
}
inline void FlowRecord::set_src_port(uint32_t value) {
  _internal_set_src_port(value);
  // @@protoc_insertion_point(field_set:ipfix.FlowRecord.SRC_PORT)
}

// uint32 DST_PORT = 4;
inline void FlowRecord::clear_dst_port() {
  _impl_.dst_port_ = 0u;
}
inline uint32_t FlowRecord::_internal_dst_port() const {
  return _impl_.dst_port_;
}
inline uint32_t FlowRecord::dst_port() const {
  // @@protoc_insertion_point(field_get:ipfix.FlowRecord.DST_PORT)
  return _internal_dst_port();
}
inline void FlowRecord::_internal_set_dst_port(uint32_t value) {
  
  _impl_.dst_port_ = value;
}
inline void FlowRecord::set_dst_port(uint32_t value) {
  _internal_set_dst_port(value);
  // @@protoc_insertion_point(field_set:ipfix.FlowRecord.DST_PORT)
}

// uint32 PROTOCOL = 5;
inline void FlowRecord::clear_protocol() {
  _impl_.protocol_ = 0u;
}
inline uint32_t FlowRecord::_internal_protocol() const {
  return _impl_.protocol_;
}
inline uint32_t FlowRecord::protocol() const {
  // @@protoc_insertion_point(field_get:ipfix.FlowRecord.PROTOCOL)
  return _internal_protocol();
}
inline void FlowRecord::_internal_set_protocol(uint32_t value) {
  
  _impl_.protocol_ = value;
}
inline void FlowRecord::set_protocol(uint32_t value) {
  _internal_set_protocol(value);
  // @@protoc_insertion_point(field_set:ipfix.FlowRecord.PROTOCOL)
}

// fixed64 BYTES = 6;
inline void FlowRecord::clear_bytes() {
  _impl_.bytes_ = uint64_t{0u};
}
inline uint64_t FlowRecord::_internal_bytes() const {
  return _impl_.bytes_;
}
inline uint64_t FlowRecord::bytes() const {
  // @@protoc_insertion_point(field_get:ipfix.FlowRecord.BYTES)
  return _internal_bytes();
}
inline void FlowRecord::_internal_set_bytes(uint64_t value) {
  
  _impl_.bytes_ = value;
}
inline void FlowRecord::set_bytes(uint64_t value) {
  _internal_set_bytes(value);
  // @@protoc_insertion_point(field_set:ipfix.FlowRecord.BYTES)
}

// fixed64 BYTES_REV = 7;
inline void FlowRecord::clear_bytes_rev() {
  _impl_.bytes_rev_ = uint64_t{0u};
}
inline uint64_t FlowRecord::_internal_bytes_rev() const {
  return _impl_.bytes_rev_;
}
inline uint64_t FlowRecord::bytes_rev() const {
  // @@protoc_insertion_point(field_get:ipfix.FlowRecord.BYTES_REV)
  return _internal_bytes_rev();
}
inline void FlowRecord::_internal_set_bytes_rev(uint64_t value) {
  
  _impl_.bytes_rev_ = value;
}
inline void FlowRecord::set_bytes_rev(uint64_t value) {
  _internal_set_bytes_rev(value);
  // @@protoc_insertion_point(field_set:ipfix.FlowRecord.BYTES_REV)
}

// fixed64 PACKETS = 8;
inline void FlowRecord::clear_packets() {
  _impl_.packets_ = uint64_t{0u};
}
inline uint64_t FlowRecord::_internal_packets() const {
  return _impl_.packets_;
}
inline uint64_t FlowRecord::packets() const {
  // @@protoc_insertion_point(field_get:ipfix.FlowRecord.PACKETS)
  return _internal_packets();
}
inline void FlowRecord::_internal_set_packets(uint64_t value) {
  
  _impl_.packets_ = value;
}
inline void FlowRecord::set_packets(uint64_t value) {
  _internal_set_packets(value);
  // @@protoc_insertion_point(field_set:ipfix.FlowRecord.PACKETS)
}

// fixed64 PACKETS_REV = 9;
inline void FlowRecord::clear_packets_rev() {
  _impl_.packets_rev_ = uint64_t{0u};
}
inline uint64_t FlowRecord::_internal_packets_rev() const {
  return _impl_.packets_rev_;
}
inline uint64_t FlowRecord::packets_rev() const {
  // @@protoc_insertion_point(field_get:ipfix.FlowRecord.PACKETS_REV)
  return _internal_packets_rev();
}
inline void FlowRecord::_internal_set_packets_rev(uint64_t value) {
  
  _impl_.packets_rev_ = value;
}
inline void FlowRecord::set_packets_rev(uint64_t value) {
  _internal_set_packets_rev(value);
  // @@protoc_insertion_point(field_set:ipfix.FlowRecord.PACKETS_REV)
}

// fixed64 TIME_FIRST = 10;
inline void FlowRecord::clear_time_first() {
  _impl_.time_first_ = uint64_t{0u};
}
inline uint64_t FlowRecord::_internal_time_first() const {
  return _impl_.time_first_;
}
inline uint64_t FlowRecord::time_first() const {
  // @@protoc_insertion_point(field_get:ipfix.FlowRecord.TIME_FIRST)
  return _internal_time_first();
}
inline void FlowRecord::_internal_set_time_first(uint64_t value) {
  
  _impl_.time_first_ = value;
}
inline void FlowRecord::set_time_first(uint64_t value) {
  _internal_set_time_first(value);
  // @@protoc_insertion_point(field_set:ipfix.FlowRecord.TIME_FIRST)
}

// fixed64 TIME_LAST = 11;
inline void FlowRecord::clear_time_last() {
  _impl_.time_last_ = uint64_t{0u};
}
inline uint64_t FlowRecord::_internal_time_last() const {
  return _impl_.time_last_;
}
inline uint64_t FlowRecord::time_last() const {
  // @@protoc_insertion_point(field_get:ipfix.FlowRecord.TIME_LAST)
  return _internal_time_last();
}
inline void FlowRecord::_internal_set_time_last(uint64_t value) {
  
  _impl_.time_last_ = value;
}
inline void FlowRecord::set_time_last(uint64_t value) {
  _internal_set_time_last(value);
  // @@protoc_insertion_point(field_set:ipfix.FlowRecord.TIME_LAST)
}

// uint32 TCP_FLAGS = 12;
inline void FlowRecord::clear_tcp_flags() {
  _impl_.tcp_flags_ = 0u;
}
inline uint32_t FlowRecord::_internal_tcp_flags() const {
  return _impl_.tcp_flags_;
}
inline uint32_t FlowRecord::tcp_flags() const {
  // @@protoc_insertion_point(field_get:ipfix.FlowRecord.TCP_FLAGS)
  return _internal_tcp_flags();
}
inline void FlowRecord::_internal_set_tcp_flags(uint32_t value) {
  
  _impl_.tcp_flags_ = value;
}
inline void FlowRecord::set_tcp_flags(uint32_t value) {
  _internal_set_tcp_flags(value);
  // @@protoc_insertion_point(field_set:ipfix.FlowRecord.TCP_FLAGS)
}

// uint32 TCP_FLAGS_REV = 13;
inline void FlowRecord::clear_tcp_flags_rev() {
  _impl_.tcp_flags_rev_ = 0u;
}
inline uint32_t FlowRecord::_internal_tcp_flags_rev() const {
  return _impl_.tcp_flags_rev_;
}
inline uint32_t FlowRecord::tcp_flags_rev() const {
  // @@protoc_insertion_point(field_get:ipfix.FlowRecord.TCP_FLAGS_REV)
  return _internal_tcp_flags_rev();
}
inline void FlowRecord::_internal_set_tcp_flags_rev(uint32_t value) {
  
  _impl_.tcp_flags_rev_ = value;
}
inline void FlowRecord::set_tcp_flags_rev(uint32_t value) {
  _internal_set_tcp_flags_rev(value);
  // @@protoc_insertion_point(field_set:ipfix.FlowRecord.TCP_FLAGS_REV)
}

// uint32 TTL = 14;
inline void FlowRecord::clear_ttl() {
  _impl_.ttl_ = 0u;
}
inline uint32_t FlowRecord::_internal_ttl() const {
  return _impl_.ttl_;
}
inline uint32_t FlowRecord::ttl() const {
  // @@protoc_insertion_point(field_get:ipfix.FlowRecord.TTL)
  return _internal_ttl();
}
inline void FlowRecord::_internal_set_ttl(uint32_t value) {
  
  _impl_.ttl_ = value;
}
inline void FlowRecord::set_ttl(uint32_t value) {
  _internal_set_ttl(value);
  // @@protoc_insertion_point(field_set:ipfix.FlowRecord.TTL)
}

// uint32 TTL_REV = 15;
inline void FlowRecord::clear_ttl_rev() {
  _impl_.ttl_rev_ = 0u;
}
inline uint32_t FlowRecord::_internal_ttl_rev() const {
  return _impl_.ttl_rev_;
}
inline uint32_t FlowRecord::ttl_rev() const {
  // @@protoc_insertion_point(field_get:ipfix.FlowRecord.TTL_REV)
  return _internal_ttl_rev();
}
inline void FlowRecord::_internal_set_ttl_rev(uint32_t value) {
  
  _impl_.ttl_rev_ = value;
}
inline void FlowRecord::set_ttl_rev(uint32_t value) {
  _internal_set_ttl_rev(value);
  // @@protoc_insertion_point(field_set:ipfix.FlowRecord.TTL_REV)
}

// uint32 FLOW_END_REASON = 16;
inline void FlowRecord::clear_flow_end_reason() {
  _impl_.flow_end_reason_ = 0u;
}
inline uint32_t FlowRecord::_internal_flow_end_reason() const {
  return _impl_.flow_end_reason_;
}
inline uint32_t FlowRecord::flow_end_reason() const {
  // @@protoc_insertion_point(field_get:ipfix.FlowRecord.FLOW_END_REASON)
  return _internal_flow_end_reason();
}
inline void FlowRecord::_internal_set_flow_end_reason(uint32_t value) {
  
  _impl_.flow_end_reason_ = value;
}
inline void FlowRecord::set_flow_end_reason(uint32_t value) {
  _internal_set_flow_end_reason(value);
  // @@protoc_insertion_point(field_set:ipfix.FlowRecord.FLOW_END_REASON)
}

// uint32 DNS_ANSWERS = 20;
inline void FlowRecord::clear_dns_answers() {
  _impl_.dns_answers_ = 0u;
}
inline uint32_t FlowRecord::_internal_dns_answers() const {
  return _impl_.dns_answers_;
}
inline uint32_t FlowRecord::dns_answers() const {
  // @@protoc_insertion_point(field_get:ipfix.FlowRecord.DNS_ANSWERS)
  return _internal_dns_answers();
}
inline void FlowRecord::_internal_set_dns_answers(uint32_t value) {
  
  _impl_.dns_answers_ = value;
}
inline void FlowRecord::set_dns_answers(uint32_t value) {
  _internal_set_dns_answers(value);
  // @@protoc_insertion_point(field_set:ipfix.FlowRecord.DNS_ANSWERS)
}

// uint32 DNS_ID = 21;
inline void FlowRecord::clear_dns_id() {
  _impl_.dns_id_ = 0u;
}
inline uint32_t FlowRecord::_internal_dns_id() const {
  return _impl_.dns_id_;
}
inline uint32_t FlowRecord::dns_id() const {
  // @@protoc_insertion_point(field_get:ipfix.FlowRecord.DNS_ID)
  return _internal_dns_id();
}
inline void FlowRecord::_internal_set_dns_id(uint32_t value) {
  
  _impl_.dns_id_ = value;
}
inline void FlowRecord::set_dns_id(uint32_t value) {
  _internal_set_dns_id(value);
  // @@protoc_insertion_point(field_set:ipfix.FlowRecord.DNS_ID)
}

// uint32 DNS_Q_TYPE = 22;
inline void FlowRecord::clear_dns_q_type() {
  _impl_.dns_q_type_ = 0u;
}
inline uint32_t FlowRecord::_internal_dns_q_type() const {
  return _impl_.dns_q_type_;
}
inline uint32_t FlowRecord::dns_q_type() const {
  // @@protoc_insertion_point(field_get:ipfix.FlowRecord.DNS_Q_TYPE)
  return _internal_dns_q_type();
}
inline void FlowRecord::_internal_set_dns_q_type(uint32_t value) {
  
  _impl_.dns_q_type_ = value;
}
inline void FlowRecord::set_dns_q_type(uint32_t value) {
  _internal_set_dns_q_type(value);
  // @@protoc_insertion_point(field_set:ipfix.FlowRecord.DNS_Q_TYPE)
}

// uint32 DNS_RR_RLENGTH = 23;
inline void FlowRecord::clear_dns_rr_rlength() {
  _impl_.dns_rr_rlength_ = 0u;
}
inline uint32_t FlowRecord::_internal_dns_rr_rlength() const {
  return _impl_.dns_rr_rlength_;
}
inline uint32_t FlowRecord::dns_rr_rlength() const {
  // @@protoc_insertion_point(field_get:ipfix.FlowRecord.DNS_RR_RLENGTH)
  return _internal_dns_rr_rlength();
}
inline void FlowRecord::_internal_set_dns_rr_rlength(uint32_t value) {
  
  _impl_.dns_rr_rlength_ = value;
}
inline void FlowRecord::set_dns_rr_rlength(uint32_t value) {
  _internal_set_dns_rr_rlength(value);
  // @@protoc_insertion_point(field_set:ipfix.FlowRecord.DNS_RR_RLENGTH)
}

// uint32 DNS_DO = 24;
inline void FlowRecord::clear_dns_do() {
  _impl_.dns_do_ = 0u;
}
inline uint32_t FlowRecord::_internal_dns_do() const {
  return _impl_.dns_do_;
}
inline uint32_t FlowRecord::dns_do() const {
  // @@protoc_insertion_point(field_get:ipfix.FlowRecord.DNS_DO)
  return _internal_dns_do();
}
inline void FlowRecord::_internal_set_dns_do(uint32_t value) {
  
  _impl_.dns_do_ = value;
}
inline void FlowRecord::set_dns_do(uint32_t value) {
  _internal_set_dns_do(value);
  // @@protoc_insertion_point(field_set:ipfix.FlowRecord.DNS_DO)
}

// uint32 DNS_RCODE = 25;
inline void FlowRecord::clear_dns_rcode() {
  _impl_.dns_rcode_ = 0u;
}
inline uint32_t FlowRecord::_internal_dns_rcode() const {
  return _impl_.dns_rcode_;
}
inline uint32_t FlowRecord::dns_rcode() const {
  // @@protoc_insertion_point(field_get:ipfix.FlowRecord.DNS_RCODE)
  return _internal_dns_rcode();
}
inline void FlowRecord::_internal_set_dns_rcode(uint32_t value) {
  
  _impl_.dns_rcode_ = value;
}
inline void FlowRecord::set_dns_rcode(uint32_t value) {
  _internal_set_dns_rcode(value);
  // @@protoc_insertion_point(field_set:ipfix.FlowRecord.DNS_RCODE)
}

// bytes DNS_Q_NAME = 26;
inline void FlowRecord::clear_dns_q_name() {
  _impl_.dns_q_name_.ClearToEmpty();
}
inline const std::string& FlowRecord::dns_q_name() const {
  // @@protoc_insertion_point(field_get:ipfix.FlowRecord.DNS_Q_NAME)
  return _internal_dns_q_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FlowRecord::set_dns_q_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.dns_q_name_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ipfix.FlowRecord.DNS_Q_NAME)
}
inline std::string* FlowRecord::mutable_dns_q_name() {
  std::string* _s = _internal_mutable_dns_q_name();
  // @@protoc_insertion_point(field_mutable:ipfix.FlowRecord.DNS_Q_NAME)
  return _s;
}
inline const std::string& FlowRecord::_internal_dns_q_name() const {
  return _impl_.dns_q_name_.Get();
}
inline void FlowRecord::_internal_set_dns_q_name(const std::string& value) {
  
  _impl_.dns_q_name_.Set(value, GetArenaForAllocation());
}
inline std::string* FlowRecord::_internal_mutable_dns_q_name() {
  
  return _impl_.dns_q_name_.Mutable(GetArenaForAllocation());
}
inline std::string* FlowRecord::release_dns_q_name() {
  // @@protoc_insertion_point(field_release:ipfix.FlowRecord.DNS_Q_NAME)
  return _impl_.dns_q_name_.Release();
}
inline void FlowRecord::set_allocated_dns_q_name(std::string* dns_q_name) {
  if (dns_q_name != nullptr) {
    
  } else {
    
  }
  _impl_.dns_q_name_.SetAllocated(dns_q_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.dns_q_name_.IsDefault()) {
    _impl_.dns_q_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ipfix.FlowRecord.DNS_Q_NAME)
}

// uint32 FME_TLS_SERVER_VERSION = 30;
inline void FlowRecord::clear_fme_tls_server_version() {
  _impl_.fme_tls_server_version_ = 0u;
}
inline uint32_t FlowRecord::_internal_fme_tls_server_version() const {
  return _impl_.fme_tls_server_version_;
}
inline uint32_t FlowRecord::fme_tls_server_version() const {
  // @@protoc_insertion_point(field_get:ipfix.FlowRecord.FME_TLS_SERVER_VERSION)
  return _internal_fme_tls_server_version();
}
inline void FlowRecord::_internal_set_fme_tls_server_version(uint32_t value) {
  
  _impl_.fme_tls_server_version_ = value;
}
inline void FlowRecord::set_fme_tls_server_version(uint32_t value) {
  _internal_set_fme_tls_server_version(value);
  // @@protoc_insertion_point(field_set:ipfix.FlowRecord.FME_TLS_SERVER_VERSION)
}

// string TLS_SNI = 31;
inline void FlowRecord::clear_tls_sni() {
  _impl_.tls_sni_.ClearToEmpty();
}
inline const std::string& FlowRecord::tls_sni() const {
  // @@protoc_insertion_point(field_get:ipfix.FlowRecord.TLS_SNI)
  return _internal_tls_sni();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FlowRecord::set_tls_sni(ArgT0&& arg0, ArgT... args) {
 
 _impl_.tls_sni_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ipfix.FlowRecord.TLS_SNI)
}
inline std::string* FlowRecord::mutable_tls_sni() {
  std::string* _s = _internal_mutable_tls_sni();
  // @@protoc_insertion_point(field_mutable:ipfix.FlowRecord.TLS_SNI)
  return _s;
}
inline const std::string& FlowRecord::_internal_tls_sni() const {
  return _impl_.tls_sni_.Get();
}
inline void FlowRecord::_internal_set_tls_sni(const std::string& value) {
  
  _impl_.tls_sni_.Set(value, GetArenaForAllocation());
}
inline std::string* FlowRecord::_internal_mutable_tls_sni() {
  
  return _impl_.tls_sni_.Mutable(GetArenaForAllocation());
}
inline std::string* FlowRecord::release_tls_sni() {
  // @@protoc_insertion_point(field_release:ipfix.FlowRecord.TLS_SNI)
  return _impl_.tls_sni_.Release();
}
inline void FlowRecord::set_allocated_tls_sni(std::string* tls_sni) {
  if (tls_sni != nullptr) {
    
  } else {
    
  }
  _impl_.tls_sni_.SetAllocated(tls_sni, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.tls_sni_.IsDefault()) {
    _impl_.tls_sni_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ipfix.FlowRecord.TLS_SNI)
}

// uint32 HTTP_RESPONSE_STATUS_CODE = 40;
inline void FlowRecord::clear_http_response_status_code() {
  _impl_.http_response_status_code_ = 0u;
}
inline uint32_t FlowRecord::_internal_http_response_status_code() const {
  return _impl_.http_response_status_code_;
}
inline uint32_t FlowRecord::http_response_status_code() const {
  // @@protoc_insertion_point(field_get:ipfix.FlowRecord.HTTP_RESPONSE_STATUS_CODE)
  return _internal_http_response_status_code();
}
inline void FlowRecord::_internal_set_http_response_status_code(uint32_t value) {
  
  _impl_.http_response_status_code_ = value;
}
inline void FlowRecord::set_http_response_status_code(uint32_t value) {
  _internal_set_http_response_status_code(value);
  // @@protoc_insertion_point(field_set:ipfix.FlowRecord.HTTP_RESPONSE_STATUS_CODE)
}

// string HTTP_REQUEST_AGENT = 41;
inline void FlowRecord::clear_http_request_agent() {
  _impl_.http_request_agent_.ClearToEmpty();
}
inline const std::string& FlowRecord::http_request_agent() const {
  // @@protoc_insertion_point(field_get:ipfix.FlowRecord.HTTP_REQUEST_AGENT)
  return _internal_http_request_agent();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FlowRecord::set_http_request_agent(ArgT0&& arg0, ArgT... args) {
 
 _impl_.http_request_agent_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ipfix.FlowRecord.HTTP_REQUEST_AGENT)
}
inline std::string* FlowRecord::mutable_http_request_agent() {
  std::string* _s = _internal_mutable_http_request_agent();
  // @@protoc_insertion_point(field_mutable:ipfix.FlowRecord.HTTP_REQUEST_AGENT)
  return _s;
}
inline const std::string& FlowRecord::_internal_http_request_agent() const {
  return _impl_.http_request_agent_.Get();
}
inline void FlowRecord::_internal_set_http_request_agent(const std::string& value) {
  
  _impl_.http_request_agent_.Set(value, GetArenaForAllocation());
}
inline std::string* FlowRecord::_internal_mutable_http_request_agent() {
  
  return _impl_.http_request_agent_.Mutable(GetArenaForAllocation());
}
inline std::string* FlowRecord::release_http_request_agent() {
  // @@protoc_insertion_point(field_release:ipfix.FlowRecord.HTTP_REQUEST_AGENT)
  return _impl_.http_request_agent_.Release();
}
inline void FlowRecord::set_allocated_http_request_agent(std::string* http_request_agent) {
  if (http_request_agent != nullptr) {
    
  } else {
    
  }
  _impl_.http_request_agent_.SetAllocated(http_request_agent, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.http_request_agent_.IsDefault()) {
    _impl_.http_request_agent_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ipfix.FlowRecord.HTTP_REQUEST_AGENT)
}

// string HTTP_REQUEST_HOST = 42;
inline void FlowRecord::clear_http_request_host() {
  _impl_.http_request_host_.ClearToEmpty();
}
inline const std::string& FlowRecord::http_request_host() const {
  // @@protoc_insertion_point(field_get:ipfix.FlowRecord.HTTP_REQUEST_HOST)
  return _internal_http_request_host();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FlowRecord::set_http_request_host(ArgT0&& arg0, ArgT... args) {
 
 _impl_.http_request_host_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ipfix.FlowRecord.HTTP_REQUEST_HOST)
}
inline std::string* FlowRecord::mutable_http_request_host() {
  std::string* _s = _internal_mutable_http_request_host();
  // @@protoc_insertion_point(field_mutable:ipfix.FlowRecord.HTTP_REQUEST_HOST)
  return _s;
}
inline const std::string& FlowRecord::_internal_http_request_host() const {
  return _impl_.http_request_host_.Get();
}
inline void FlowRecord::_internal_set_http_request_host(const std::string& value) {
  
  _impl_.http_request_host_.Set(value, GetArenaForAllocation());
}
inline std::string* FlowRecord::_internal_mutable_http_request_host() {
  
  return _impl_.http_request_host_.Mutable(GetArenaForAllocation());
}
inline std::string* FlowRecord::release_http_request_host() {
  // @@protoc_insertion_point(field_release:ipfix.FlowRecord.HTTP_REQUEST_HOST)
  return _impl_.http_request_host_.Release();
}
inline void FlowRecord::set_allocated_http_request_host(std::string* http_request_host) {
  if (http_request_host != nullptr) {
    
  } else {
    
  }
  _impl_.http_request_host_.SetAllocated(http_request_host, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.http_request_host_.IsDefault()) {
    _impl_.http_request_host_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ipfix.FlowRecord.HTTP_REQUEST_HOST)
}

// string HTTP_REQUEST_REFERER = 43;
inline void FlowRecord::clear_http_request_referer() {
  _impl_.http_request_referer_.ClearToEmpty();
}
inline const std::string& FlowRecord::http_request_referer() const {
  // @@protoc_insertion_point(field_get:ipfix.FlowRecord.HTTP_REQUEST_REFERER)
  return _internal_http_request_referer();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FlowRecord::set_http_request_referer(ArgT0&& arg0, ArgT... args) {
 
 _impl_.http_request_referer_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ipfix.FlowRecord.HTTP_REQUEST_REFERER)
}
inline std::string* FlowRecord::mutable_http_request_referer() {
  std::string* _s = _internal_mutable_http_request_referer();
  // @@protoc_insertion_point(field_mutable:ipfix.FlowRecord.HTTP_REQUEST_REFERER)
  return _s;
}
inline const std::string& FlowRecord::_internal_http_request_referer() const {
  return _impl_.http_request_referer_.Get();
}
inline void FlowRecord::_internal_set_http_request_referer(const std::string& value) {
  
  _impl_.http_request_referer_.Set(value, GetArenaForAllocation());
}
inline std::string* FlowRecord::_internal_mutable_http_request_referer() {
  
  return _impl_.http_request_referer_.Mutable(GetArenaForAllocation());
}
inline std::string* FlowRecord::release_http_request_referer() {
  // @@protoc_insertion_point(field_release:ipfix.FlowRecord.HTTP_REQUEST_REFERER)
  return _impl_.http_request_referer_.Release();
}
inline void FlowRecord::set_allocated_http_request_referer(std::string* http_request_referer) {
  if (http_request_referer != nullptr) {
    
  } else {
    
  }
  _impl_.http_request_referer_.SetAllocated(http_request_referer, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.http_request_referer_.IsDefault()) {
    _impl_.http_request_referer_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ipfix.FlowRecord.HTTP_REQUEST_REFERER)
}

// string HTTP_REQUEST_URL = 44;
inline void FlowRecord::clear_http_request_url() {
  _impl_.http_request_url_.ClearToEmpty();
}
inline const std::string& FlowRecord::http_request_url() const {
  // @@protoc_insertion_point(field_get:ipfix.FlowRecord.HTTP_REQUEST_URL)
  return _internal_http_request_url();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FlowRecord::set_http_request_url(ArgT0&& arg0, ArgT... args) {
 
 _impl_.http_request_url_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ipfix.FlowRecord.HTTP_REQUEST_URL)
}
inline std::string* FlowRecord::mutable_http_request_url() {
  std::string* _s = _internal_mutable_http_request_url();
  // @@protoc_insertion_point(field_mutable:ipfix.FlowRecord.HTTP_REQUEST_URL)
  return _s;
}
inline const std::string& FlowRecord::_internal_http_request_url() const {
  return _impl_.http_request_url_.Get();
}
inline void FlowRecord::_internal_set_http_request_url(const std::string& value) {
  
  _impl_.http_request_url_.Set(value, GetArenaForAllocation());
}
inline std::string* FlowRecord::_internal_mutable_http_request_url() {
  
  return _impl_.http_request_url_.Mutable(GetArenaForAllocation());
}
inline std::string* FlowRecord::release_http_request_url() {
  // @@protoc_insertion_point(field_release:ipfix.FlowRecord.HTTP_REQUEST_URL)
  return _impl_.http_request_url_.Release();
}
inline void FlowRecord::set_allocated_http_request_url(std::string* http_request_url) {
  if (http_request_url != nullptr) {
    
  } else {
    
  }
  _impl_.http_request_url_.SetAllocated(http_request_url, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.http_request_url_.IsDefault()) {
    _impl_.http_request_url_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ipfix.FlowRecord.HTTP_REQUEST_URL)
}

// string HTTP_RESPONSE_CONTENT_TYPE = 45;
inline void FlowRecord::clear_http_response_content_type() {
  _impl_.http_response_content_type_.ClearToEmpty();
}
inline const std::string& FlowRecord::http_response_content_type() const {
  // @@protoc_insertion_point(field_get:ipfix.FlowRecord.HTTP_RESPONSE_CONTENT_TYPE)
  return _internal_http_response_content_type();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FlowRecord::set_http_response_content_type(ArgT0&& arg0, ArgT... args) {
 
 _impl_.http_response_content_type_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ipfix.FlowRecord.HTTP_RESPONSE_CONTENT_TYPE)
}
inline std::string* FlowRecord::mutable_http_response_content_type() {
  std::string* _s = _internal_mutable_http_response_content_type();
  // @@protoc_insertion_point(field_mutable:ipfix.FlowRecord.HTTP_RESPONSE_CONTENT_TYPE)
  return _s;
}
inline const std::string& FlowRecord::_internal_http_response_content_type() const {
  return _impl_.http_response_content_type_.Get();
}
inline void FlowRecord::_internal_set_http_response_content_type(const std::string& value) {
  
  _impl_.http_response_content_type_.Set(value, GetArenaForAllocation());
}
inline std::string* FlowRecord::_internal_mutable_http_response_content_type() {
  
  return _impl_.http_response_content_type_.Mutable(GetArenaForAllocation());
}
inline std::string* FlowRecord::release_http_response_content_type() {
  // @@protoc_insertion_point(field_release:ipfix.FlowRecord.HTTP_RESPONSE_CONTENT_TYPE)
  return _impl_.http_response_content_type_.Release();
}
inline void FlowRecord::set_allocated_http_response_content_type(std::string* http_response_content_type) {
  if (http_response_content_type != nullptr) {
    
  } else {
    
  }
  _impl_.http_response_content_type_.SetAllocated(http_response_content_type, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.http_response_content_type_.IsDefault()) {
    _impl_.http_response_content_type_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ipfix.FlowRecord.HTTP_RESPONSE_CONTENT_TYPE)
}

// uint64 FLOW_ID = 50;
inline void FlowRecord::clear_flow_id() {
  _impl_.flow_id_ = uint64_t{0u};
}
inline uint64_t FlowRecord::_internal_flow_id() const {
  return _impl_.flow_id_;
}
inline uint64_t FlowRecord::flow_id() const {
  // @@protoc_insertion_point(field_get:ipfix.FlowRecord.FLOW_ID)
  return _internal_flow_id();
}
inline void FlowRecord::_internal_set_flow_id(uint64_t value) {
  
  _impl_.flow_id_ = value;
}
inline void FlowRecord::set_flow_id(uint64_t value) {
  _internal_set_flow_id(value);
  // @@protoc_insertion_point(field_set:ipfix.FlowRecord.FLOW_ID)
}

// uint64 FLOW_COUNT = 51;
inline void FlowRecord::clear_flow_count() {
  _impl_.flow_count_ = uint64_t{0u};
}
inline uint64_t FlowRecord::_internal_flow_count() const {
  return _impl_.flow_count_;
}
inline uint64_t FlowRecord::flow_count() const {
  // @@protoc_insertion_point(field_get:ipfix.FlowRecord.FLOW_COUNT)
  return _internal_flow_count();
}
inline void FlowRecord::_internal_set_flow_count(uint64_t value) {
  
  _impl_.flow_count_ = value;
}
inline void FlowRecord::set_flow_count(uint64_t value) {
  _internal_set_flow_count(value);
  // @@protoc_insertion_point(field_set:ipfix.FlowRecord.FLOW_COUNT)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace ipfix

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_schema
