// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema

#include "schema.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace ipfix {
PROTOBUF_CONSTEXPR FlowRecord::FlowRecord(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.src_ip_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.dst_ip_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.dns_q_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.tls_sni_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.http_request_agent_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.http_request_host_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.http_request_referer_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.http_request_url_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.http_response_content_type_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.src_port_)*/0u
  , /*decltype(_impl_.dst_port_)*/0u
  , /*decltype(_impl_.bytes_)*/uint64_t{0u}
  , /*decltype(_impl_.bytes_rev_)*/uint64_t{0u}
  , /*decltype(_impl_.packets_)*/uint64_t{0u}
  , /*decltype(_impl_.protocol_)*/0u
  , /*decltype(_impl_.tcp_flags_)*/0u
  , /*decltype(_impl_.packets_rev_)*/uint64_t{0u}
  , /*decltype(_impl_.time_first_)*/uint64_t{0u}
  , /*decltype(_impl_.time_last_)*/uint64_t{0u}
  , /*decltype(_impl_.tcp_flags_rev_)*/0u
  , /*decltype(_impl_.ttl_)*/0u
  , /*decltype(_impl_.ttl_rev_)*/0u
  , /*decltype(_impl_.flow_end_reason_)*/0u
  , /*decltype(_impl_.dns_answers_)*/0u
  , /*decltype(_impl_.dns_id_)*/0u
  , /*decltype(_impl_.dns_q_type_)*/0u
  , /*decltype(_impl_.dns_rr_rlength_)*/0u
  , /*decltype(_impl_.dns_do_)*/0u
  , /*decltype(_impl_.dns_rcode_)*/0u
  , /*decltype(_impl_.fme_tls_server_version_)*/0u
  , /*decltype(_impl_.http_response_status_code_)*/0u
  , /*decltype(_impl_.flow_id_)*/uint64_t{0u}
  , /*decltype(_impl_.flow_count_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct FlowRecordDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FlowRecordDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~FlowRecordDefaultTypeInternal() {}
  union {
    FlowRecord _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FlowRecordDefaultTypeInternal _FlowRecord_default_instance_;
}  // namespace ipfix
static ::_pb::Metadata file_level_metadata_schema[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_schema = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_schema = nullptr;

const uint32_t TableStruct_schema::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ipfix::FlowRecord, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ipfix::FlowRecord, _impl_.src_ip_),
  PROTOBUF_FIELD_OFFSET(::ipfix::FlowRecord, _impl_.dst_ip_),
  PROTOBUF_FIELD_OFFSET(::ipfix::FlowRecord, _impl_.src_port_),
  PROTOBUF_FIELD_OFFSET(::ipfix::FlowRecord, _impl_.dst_port_),
  PROTOBUF_FIELD_OFFSET(::ipfix::FlowRecord, _impl_.protocol_),
  PROTOBUF_FIELD_OFFSET(::ipfix::FlowRecord, _impl_.bytes_),
  PROTOBUF_FIELD_OFFSET(::ipfix::FlowRecord, _impl_.bytes_rev_),
  PROTOBUF_FIELD_OFFSET(::ipfix::FlowRecord, _impl_.packets_),
  PROTOBUF_FIELD_OFFSET(::ipfix::FlowRecord, _impl_.packets_rev_),
  PROTOBUF_FIELD_OFFSET(::ipfix::FlowRecord, _impl_.time_first_),
  PROTOBUF_FIELD_OFFSET(::ipfix::FlowRecord, _impl_.time_last_),
  PROTOBUF_FIELD_OFFSET(::ipfix::FlowRecord, _impl_.tcp_flags_),
  PROTOBUF_FIELD_OFFSET(::ipfix::FlowRecord, _impl_.tcp_flags_rev_),
  PROTOBUF_FIELD_OFFSET(::ipfix::FlowRecord, _impl_.ttl_),
  PROTOBUF_FIELD_OFFSET(::ipfix::FlowRecord, _impl_.ttl_rev_),
  PROTOBUF_FIELD_OFFSET(::ipfix::FlowRecord, _impl_.flow_end_reason_),
  PROTOBUF_FIELD_OFFSET(::ipfix::FlowRecord, _impl_.dns_answers_),
  PROTOBUF_FIELD_OFFSET(::ipfix::FlowRecord, _impl_.dns_id_),
  PROTOBUF_FIELD_OFFSET(::ipfix::FlowRecord, _impl_.dns_q_type_),
  PROTOBUF_FIELD_OFFSET(::ipfix::FlowRecord, _impl_.dns_rr_rlength_),
  PROTOBUF_FIELD_OFFSET(::ipfix::FlowRecord, _impl_.dns_do_),
  PROTOBUF_FIELD_OFFSET(::ipfix::FlowRecord, _impl_.dns_rcode_),
  PROTOBUF_FIELD_OFFSET(::ipfix::FlowRecord, _impl_.dns_q_name_),
  PROTOBUF_FIELD_OFFSET(::ipfix::FlowRecord, _impl_.fme_tls_server_version_),
  PROTOBUF_FIELD_OFFSET(::ipfix::FlowRecord, _impl_.tls_sni_),
  PROTOBUF_FIELD_OFFSET(::ipfix::FlowRecord, _impl_.http_response_status_code_),
  PROTOBUF_FIELD_OFFSET(::ipfix::FlowRecord, _impl_.http_request_agent_),
  PROTOBUF_FIELD_OFFSET(::ipfix::FlowRecord, _impl_.http_request_host_),
  PROTOBUF_FIELD_OFFSET(::ipfix::FlowRecord, _impl_.http_request_referer_),
  PROTOBUF_FIELD_OFFSET(::ipfix::FlowRecord, _impl_.http_request_url_),
  PROTOBUF_FIELD_OFFSET(::ipfix::FlowRecord, _impl_.http_response_content_type_),
  PROTOBUF_FIELD_OFFSET(::ipfix::FlowRecord, _impl_.flow_id_),
  PROTOBUF_FIELD_OFFSET(::ipfix::FlowRecord, _impl_.flow_count_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::ipfix::FlowRecord)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::ipfix::_FlowRecord_default_instance_._instance,
};

const char descriptor_table_protodef_schema[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\006schema\022\005ipfix\"\306\005\n\nFlowRecord\022\016\n\006SRC_IP"
  "\030\001 \001(\014\022\016\n\006DST_IP\030\002 \001(\014\022\020\n\010SRC_PORT\030\003 \001(\r"
  "\022\020\n\010DST_PORT\030\004 \001(\r\022\020\n\010PROTOCOL\030\005 \001(\r\022\r\n\005"
  "BYTES\030\006 \001(\006\022\021\n\tBYTES_REV\030\007 \001(\006\022\017\n\007PACKET"
  "S\030\010 \001(\006\022\023\n\013PACKETS_REV\030\t \001(\006\022\022\n\nTIME_FIR"
  "ST\030\n \001(\006\022\021\n\tTIME_LAST\030\013 \001(\006\022\021\n\tTCP_FLAGS"
  "\030\014 \001(\r\022\025\n\rTCP_FLAGS_REV\030\r \001(\r\022\013\n\003TTL\030\016 \001"
  "(\r\022\017\n\007TTL_REV\030\017 \001(\r\022\027\n\017FLOW_END_REASON\030\020"
  " \001(\r\022\023\n\013DNS_ANSWERS\030\024 \001(\r\022\016\n\006DNS_ID\030\025 \001("
  "\r\022\022\n\nDNS_Q_TYPE\030\026 \001(\r\022\026\n\016DNS_RR_RLENGTH\030"
  "\027 \001(\r\022\016\n\006DNS_DO\030\030 \001(\r\022\021\n\tDNS_RCODE\030\031 \001(\r"
  "\022\022\n\nDNS_Q_NAME\030\032 \001(\014\022\036\n\026FME_TLS_SERVER_V"
  "ERSION\030\036 \001(\r\022\017\n\007TLS_SNI\030\037 \001(\t\022!\n\031HTTP_RE"
  "SPONSE_STATUS_CODE\030( \001(\r\022\032\n\022HTTP_REQUEST"
  "_AGENT\030) \001(\t\022\031\n\021HTTP_REQUEST_HOST\030* \001(\t\022"
  "\034\n\024HTTP_REQUEST_REFERER\030+ \001(\t\022\030\n\020HTTP_RE"
  "QUEST_URL\030, \001(\t\022\"\n\032HTTP_RESPONSE_CONTENT"
  "_TYPE\030- \001(\t\022\017\n\007FLOW_ID\0302 \001(\004\022\022\n\nFLOW_COU"
  "NT\0303 \001(\004B\002H\001b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_schema_once;
const ::_pbi::DescriptorTable descriptor_table_schema = {
    false, false, 740, descriptor_table_protodef_schema,
    "schema",
    &descriptor_table_schema_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_schema::offsets,
    file_level_metadata_schema, file_level_enum_descriptors_schema,
    file_level_service_descriptors_schema,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_schema_getter() {
  return &descriptor_table_schema;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_schema(&descriptor_table_schema);
namespace ipfix {

// ===================================================================

class FlowRecord::_Internal {
 public:
};

FlowRecord::FlowRecord(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ipfix.FlowRecord)
}
FlowRecord::FlowRecord(const FlowRecord& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  FlowRecord* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.src_ip_){}
    , decltype(_impl_.dst_ip_){}
    , decltype(_impl_.dns_q_name_){}
    , decltype(_impl_.tls_sni_){}
    , decltype(_impl_.http_request_agent_){}
    , decltype(_impl_.http_request_host_){}
    , decltype(_impl_.http_request_referer_){}
    , decltype(_impl_.http_request_url_){}
    , decltype(_impl_.http_response_content_type_){}
    , decltype(_impl_.src_port_){}
    , decltype(_impl_.dst_port_){}
    , decltype(_impl_.bytes_){}
    , decltype(_impl_.bytes_rev_){}
    , decltype(_impl_.packets_){}
    , decltype(_impl_.protocol_){}
    , decltype(_impl_.tcp_flags_){}
    , decltype(_impl_.packets_rev_){}
    , decltype(_impl_.time_first_){}
    , decltype(_impl_.time_last_){}
    , decltype(_impl_.tcp_flags_rev_){}
    , decltype(_impl_.ttl_){}
    , decltype(_impl_.ttl_rev_){}
    , decltype(_impl_.flow_end_reason_){}
    , decltype(_impl_.dns_answers_){}
    , decltype(_impl_.dns_id_){}
    , decltype(_impl_.dns_q_type_){}
    , decltype(_impl_.dns_rr_rlength_){}
    , decltype(_impl_.dns_do_){}
    , decltype(_impl_.dns_rcode_){}
    , decltype(_impl_.fme_tls_server_version_){}
    , decltype(_impl_.http_response_status_code_){}
    , decltype(_impl_.flow_id_){}
    , decltype(_impl_.flow_count_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.src_ip_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.src_ip_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_src_ip().empty()) {
    _this->_impl_.src_ip_.Set(from._internal_src_ip(), 
      _this->GetArenaForAllocation());
  }
  _impl_.dst_ip_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.dst_ip_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_dst_ip().empty()) {
    _this->_impl_.dst_ip_.Set(from._internal_dst_ip(), 
      _this->GetArenaForAllocation());
  }
  _impl_.dns_q_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.dns_q_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_dns_q_name().empty()) {
    _this->_impl_.dns_q_name_.Set(from._internal_dns_q_name(), 
      _this->GetArenaForAllocation());
  }
  _impl_.tls_sni_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.tls_sni_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_tls_sni().empty()) {
    _this->_impl_.tls_sni_.Set(from._internal_tls_sni(), 
      _this->GetArenaForAllocation());
  }
  _impl_.http_request_agent_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.http_request_agent_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_http_request_agent().empty()) {
    _this->_impl_.http_request_agent_.Set(from._internal_http_request_agent(), 
      _this->GetArenaForAllocation());
  }
  _impl_.http_request_host_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.http_request_host_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_http_request_host().empty()) {
    _this->_impl_.http_request_host_.Set(from._internal_http_request_host(), 
      _this->GetArenaForAllocation());
  }
  _impl_.http_request_referer_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.http_request_referer_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_http_request_referer().empty()) {
    _this->_impl_.http_request_referer_.Set(from._internal_http_request_referer(), 
      _this->GetArenaForAllocation());
  }
  _impl_.http_request_url_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.http_request_url_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_http_request_url().empty()) {
    _this->_impl_.http_request_url_.Set(from._internal_http_request_url(), 
      _this->GetArenaForAllocation());
  }
  _impl_.http_response_content_type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.http_response_content_type_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_http_response_content_type().empty()) {
    _this->_impl_.http_response_content_type_.Set(from._internal_http_response_content_type(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.src_port_, &from._impl_.src_port_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.flow_count_) -
    reinterpret_cast<char*>(&_impl_.src_port_)) + sizeof(_impl_.flow_count_));
  // @@protoc_insertion_point(copy_constructor:ipfix.FlowRecord)
}

inline void FlowRecord::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.src_ip_){}
    , decltype(_impl_.dst_ip_){}
    , decltype(_impl_.dns_q_name_){}
    , decltype(_impl_.tls_sni_){}
    , decltype(_impl_.http_request_agent_){}
    , decltype(_impl_.http_request_host_){}
    , decltype(_impl_.http_request_referer_){}
    , decltype(_impl_.http_request_url_){}
    , decltype(_impl_.http_response_content_type_){}
    , decltype(_impl_.src_port_){0u}
    , decltype(_impl_.dst_port_){0u}
    , decltype(_impl_.bytes_){uint64_t{0u}}
    , decltype(_impl_.bytes_rev_){uint64_t{0u}}
    , decltype(_impl_.packets_){uint64_t{0u}}
    , decltype(_impl_.protocol_){0u}
    , decltype(_impl_.tcp_flags_){0u}
    , decltype(_impl_.packets_rev_){uint64_t{0u}}
    , decltype(_impl_.time_first_){uint64_t{0u}}
    , decltype(_impl_.time_last_){uint64_t{0u}}
    , decltype(_impl_.tcp_flags_rev_){0u}
    , decltype(_impl_.ttl_){0u}
    , decltype(_impl_.ttl_rev_){0u}
    , decltype(_impl_.flow_end_reason_){0u}
    , decltype(_impl_.dns_answers_){0u}
    , decltype(_impl_.dns_id_){0u}
    , decltype(_impl_.dns_q_type_){0u}
    , decltype(_impl_.dns_rr_rlength_){0u}
    , decltype(_impl_.dns_do_){0u}
    , decltype(_impl_.dns_rcode_){0u}
    , decltype(_impl_.fme_tls_server_version_){0u}
    , decltype(_impl_.http_response_status_code_){0u}
    , decltype(_impl_.flow_id_){uint64_t{0u}}
    , decltype(_impl_.flow_count_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.src_ip_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.src_ip_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.dst_ip_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.dst_ip_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.dns_q_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.dns_q_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.tls_sni_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.tls_sni_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.http_request_agent_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.http_request_agent_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.http_request_host_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.http_request_host_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.http_request_referer_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.http_request_referer_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.http_request_url_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.http_request_url_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.http_response_content_type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.http_response_content_type_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

FlowRecord::~FlowRecord() {
  // @@protoc_insertion_point(destructor:ipfix.FlowRecord)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void FlowRecord::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.src_ip_.Destroy();
  _impl_.dst_ip_.Destroy();
  _impl_.dns_q_name_.Destroy();
  _impl_.tls_sni_.Destroy();
  _impl_.http_request_agent_.Destroy();
  _impl_.http_request_host_.Destroy();
  _impl_.http_request_referer_.Destroy();
  _impl_.http_request_url_.Destroy();
  _impl_.http_response_content_type_.Destroy();
}

void FlowRecord::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void FlowRecord::Clear() {
// @@protoc_insertion_point(message_clear_start:ipfix.FlowRecord)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.src_ip_.ClearToEmpty();
  _impl_.dst_ip_.ClearToEmpty();
  _impl_.dns_q_name_.ClearToEmpty();
  _impl_.tls_sni_.ClearToEmpty();
  _impl_.http_request_agent_.ClearToEmpty();
  _impl_.http_request_host_.ClearToEmpty();
  _impl_.http_request_referer_.ClearToEmpty();
  _impl_.http_request_url_.ClearToEmpty();
  _impl_.http_response_content_type_.ClearToEmpty();
  ::memset(&_impl_.src_port_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.flow_count_) -
      reinterpret_cast<char*>(&_impl_.src_port_)) + sizeof(_impl_.flow_count_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* FlowRecord::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bytes SRC_IP = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_src_ip();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes DST_IP = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_dst_ip();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 SRC_PORT = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.src_port_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 DST_PORT = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.dst_port_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 PROTOCOL = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.protocol_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // fixed64 BYTES = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 49)) {
          _impl_.bytes_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<uint64_t>(ptr);
          ptr += sizeof(uint64_t);
        } else
          goto handle_unusual;
        continue;
      // fixed64 BYTES_REV = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 57)) {
          _impl_.bytes_rev_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<uint64_t>(ptr);
          ptr += sizeof(uint64_t);
        } else
          goto handle_unusual;
        continue;
      // fixed64 PACKETS = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 65)) {
          _impl_.packets_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<uint64_t>(ptr);
          ptr += sizeof(uint64_t);
        } else
          goto handle_unusual;
        continue;
      // fixed64 PACKETS_REV = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 73)) {
          _impl_.packets_rev_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<uint64_t>(ptr);
          ptr += sizeof(uint64_t);
        } else
          goto handle_unusual;
        continue;
      // fixed64 TIME_FIRST = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 81)) {
          _impl_.time_first_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<uint64_t>(ptr);
          ptr += sizeof(uint64_t);
        } else
          goto handle_unusual;
        continue;
      // fixed64 TIME_LAST = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 89)) {
          _impl_.time_last_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<uint64_t>(ptr);
          ptr += sizeof(uint64_t);
        } else
          goto handle_unusual;
        continue;
      // uint32 TCP_FLAGS = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 96)) {
          _impl_.tcp_flags_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 TCP_FLAGS_REV = 13;
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 104)) {
          _impl_.tcp_flags_rev_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 TTL = 14;
      case 14:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 112)) {
          _impl_.ttl_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 TTL_REV = 15;
      case 15:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 120)) {
          _impl_.ttl_rev_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 FLOW_END_REASON = 16;
      case 16:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 128)) {
          _impl_.flow_end_reason_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 DNS_ANSWERS = 20;
      case 20:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 160)) {
          _impl_.dns_answers_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 DNS_ID = 21;
      case 21:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 168)) {
          _impl_.dns_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 DNS_Q_TYPE = 22;
      case 22:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 176)) {
          _impl_.dns_q_type_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 DNS_RR_RLENGTH = 23;
      case 23:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 184)) {
          _impl_.dns_rr_rlength_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 DNS_DO = 24;
      case 24:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 192)) {
          _impl_.dns_do_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 DNS_RCODE = 25;
      case 25:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 200)) {
          _impl_.dns_rcode_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes DNS_Q_NAME = 26;
      case 26:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 210)) {
          auto str = _internal_mutable_dns_q_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 FME_TLS_SERVER_VERSION = 30;
      case 30:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 240)) {
          _impl_.fme_tls_server_version_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string TLS_SNI = 31;
      case 31:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 250)) {
          auto str = _internal_mutable_tls_sni();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ipfix.FlowRecord.TLS_SNI"));
        } else
          goto handle_unusual;
        continue;
      // uint32 HTTP_RESPONSE_STATUS_CODE = 40;
      case 40:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 64)) {
          _impl_.http_response_status_code_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string HTTP_REQUEST_AGENT = 41;
      case 41:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 74)) {
          auto str = _internal_mutable_http_request_agent();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ipfix.FlowRecord.HTTP_REQUEST_AGENT"));
        } else
          goto handle_unusual;
        continue;
      // string HTTP_REQUEST_HOST = 42;
      case 42:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 82)) {
          auto str = _internal_mutable_http_request_host();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ipfix.FlowRecord.HTTP_REQUEST_HOST"));
        } else
          goto handle_unusual;
        continue;
      // string HTTP_REQUEST_REFERER = 43;
      case 43:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 90)) {
          auto str = _internal_mutable_http_request_referer();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ipfix.FlowRecord.HTTP_REQUEST_REFERER"));
        } else
          goto handle_unusual;
        continue;
      // string HTTP_REQUEST_URL = 44;
      case 44:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 98)) {
          auto str = _internal_mutable_http_request_url();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ipfix.FlowRecord.HTTP_REQUEST_URL"));
        } else
          goto handle_unusual;
        continue;
      // string HTTP_RESPONSE_CONTENT_TYPE = 45;
      case 45:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 106)) {
          auto str = _internal_mutable_http_response_content_type();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ipfix.FlowRecord.HTTP_RESPONSE_CONTENT_TYPE"));
        } else
          goto handle_unusual;
        continue;
      // uint64 FLOW_ID = 50;
      case 50:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 144)) {
          _impl_.flow_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 FLOW_COUNT = 51;
      case 51:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 152)) {
          _impl_.flow_count_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* FlowRecord::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ipfix.FlowRecord)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes SRC_IP = 1;
  if (!this->_internal_src_ip().empty()) {
    target = stream->WriteBytesMaybeAliased(
        1, this->_internal_src_ip(), target);
  }

  // bytes DST_IP = 2;
  if (!this->_internal_dst_ip().empty()) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_dst_ip(), target);
  }

  // uint32 SRC_PORT = 3;
  if (this->_internal_src_port() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_src_port(), target);
  }

  // uint32 DST_PORT = 4;
  if (this->_internal_dst_port() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(4, this->_internal_dst_port(), target);
  }

  // uint32 PROTOCOL = 5;
  if (this->_internal_protocol() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(5, this->_internal_protocol(), target);
  }

  // fixed64 BYTES = 6;
  if (this->_internal_bytes() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFixed64ToArray(6, this->_internal_bytes(), target);
  }

  // fixed64 BYTES_REV = 7;
  if (this->_internal_bytes_rev() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFixed64ToArray(7, this->_internal_bytes_rev(), target);
  }

  // fixed64 PACKETS = 8;
  if (this->_internal_packets() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFixed64ToArray(8, this->_internal_packets(), target);
  }

  // fixed64 PACKETS_REV = 9;
  if (this->_internal_packets_rev() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFixed64ToArray(9, this->_internal_packets_rev(), target);
  }

  // fixed64 TIME_FIRST = 10;
  if (this->_internal_time_first() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFixed64ToArray(10, this->_internal_time_first(), target);
  }

  // fixed64 TIME_LAST = 11;
  if (this->_internal_time_last() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFixed64ToArray(11, this->_internal_time_last(), target);
  }

  // uint32 TCP_FLAGS = 12;
  if (this->_internal_tcp_flags() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(12, this->_internal_tcp_flags(), target);
  }

  // uint32 TCP_FLAGS_REV = 13;
  if (this->_internal_tcp_flags_rev() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(13, this->_internal_tcp_flags_rev(), target);
  }

  // uint32 TTL = 14;
  if (this->_internal_ttl() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(14, this->_internal_ttl(), target);
  }

  // uint32 TTL_REV = 15;
  if (this->_internal_ttl_rev() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(15, this->_internal_ttl_rev(), target);
  }

  // uint32 FLOW_END_REASON = 16;
  if (this->_internal_flow_end_reason() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(16, this->_internal_flow_end_reason(), target);
  }

  // uint32 DNS_ANSWERS = 20;
  if (this->_internal_dns_answers() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(20, this->_internal_dns_answers(), target);
  }

  // uint32 DNS_ID = 21;
  if (this->_internal_dns_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(21, this->_internal_dns_id(), target);
  }

  // uint32 DNS_Q_TYPE = 22;
  if (this->_internal_dns_q_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(22, this->_internal_dns_q_type(), target);
  }

  // uint32 DNS_RR_RLENGTH = 23;
  if (this->_internal_dns_rr_rlength() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(23, this->_internal_dns_rr_rlength(), target);
  }

  // uint32 DNS_DO = 24;
  if (this->_internal_dns_do() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(24, this->_internal_dns_do(), target);
  }

  // uint32 DNS_RCODE = 25;
  if (this->_internal_dns_rcode() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(25, this->_internal_dns_rcode(), target);
  }

  // bytes DNS_Q_NAME = 26;
  if (!this->_internal_dns_q_name().empty()) {
    target = stream->WriteBytesMaybeAliased(
        26, this->_internal_dns_q_name(), target);
  }

  // uint32 FME_TLS_SERVER_VERSION = 30;
  if (this->_internal_fme_tls_server_version() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(30, this->_internal_fme_tls_server_version(), target);
  }

  // string TLS_SNI = 31;
  if (!this->_internal_tls_sni().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_tls_sni().data(), static_cast<int>(this->_internal_tls_sni().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ipfix.FlowRecord.TLS_SNI");
    target = stream->WriteStringMaybeAliased(
        31, this->_internal_tls_sni(), target);
  }

  // uint32 HTTP_RESPONSE_STATUS_CODE = 40;
  if (this->_internal_http_response_status_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(40, this->_internal_http_response_status_code(), target);
  }

  // string HTTP_REQUEST_AGENT = 41;
  if (!this->_internal_http_request_agent().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_http_request_agent().data(), static_cast<int>(this->_internal_http_request_agent().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ipfix.FlowRecord.HTTP_REQUEST_AGENT");
    target = stream->WriteStringMaybeAliased(
        41, this->_internal_http_request_agent(), target);
  }

  // string HTTP_REQUEST_HOST = 42;
  if (!this->_internal_http_request_host().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_http_request_host().data(), static_cast<int>(this->_internal_http_request_host().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ipfix.FlowRecord.HTTP_REQUEST_HOST");
    target = stream->WriteStringMaybeAliased(
        42, this->_internal_http_request_host(), target);
  }

  // string HTTP_REQUEST_REFERER = 43;
  if (!this->_internal_http_request_referer().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_http_request_referer().data(), static_cast<int>(this->_internal_http_request_referer().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ipfix.FlowRecord.HTTP_REQUEST_REFERER");
    target = stream->WriteStringMaybeAliased(
        43, this->_internal_http_request_referer(), target);
  }

  // string HTTP_REQUEST_URL = 44;
  if (!this->_internal_http_request_url().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_http_request_url().data(), static_cast<int>(this->_internal_http_request_url().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ipfix.FlowRecord.HTTP_REQUEST_URL");
    target = stream->WriteStringMaybeAliased(
        44, this->_internal_http_request_url(), target);
  }

  // string HTTP_RESPONSE_CONTENT_TYPE = 45;
  if (!this->_internal_http_response_content_type().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_http_response_content_type().data(), static_cast<int>(this->_internal_http_response_content_type().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ipfix.FlowRecord.HTTP_RESPONSE_CONTENT_TYPE");
    target = stream->WriteStringMaybeAliased(
        45, this->_internal_http_response_content_type(), target);
  }

  // uint64 FLOW_ID = 50;
  if (this->_internal_flow_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(50, this->_internal_flow_id(), target);
  }

  // uint64 FLOW_COUNT = 51;
  if (this->_internal_flow_count() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(51, this->_internal_flow_count(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ipfix.FlowRecord)
  return target;
}

size_t FlowRecord::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ipfix.FlowRecord)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes SRC_IP = 1;
  if (!this->_internal_src_ip().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_src_ip());
  }

  // bytes DST_IP = 2;
  if (!this->_internal_dst_ip().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_dst_ip());
  }

  // bytes DNS_Q_NAME = 26;
  if (!this->_internal_dns_q_name().empty()) {
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_dns_q_name());
  }

  // string TLS_SNI = 31;
  if (!this->_internal_tls_sni().empty()) {
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_tls_sni());
  }

  // string HTTP_REQUEST_AGENT = 41;
  if (!this->_internal_http_request_agent().empty()) {
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_http_request_agent());
  }

  // string HTTP_REQUEST_HOST = 42;
  if (!this->_internal_http_request_host().empty()) {
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_http_request_host());
  }

  // string HTTP_REQUEST_REFERER = 43;
  if (!this->_internal_http_request_referer().empty()) {
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_http_request_referer());
  }

  // string HTTP_REQUEST_URL = 44;
  if (!this->_internal_http_request_url().empty()) {
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_http_request_url());
  }

  // string HTTP_RESPONSE_CONTENT_TYPE = 45;
  if (!this->_internal_http_response_content_type().empty()) {
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_http_response_content_type());
  }

  // uint32 SRC_PORT = 3;
  if (this->_internal_src_port() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_src_port());
  }

  // uint32 DST_PORT = 4;
  if (this->_internal_dst_port() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_dst_port());
  }

  // fixed64 BYTES = 6;
  if (this->_internal_bytes() != 0) {
    total_size += 1 + 8;
  }

  // fixed64 BYTES_REV = 7;
  if (this->_internal_bytes_rev() != 0) {
    total_size += 1 + 8;
  }

  // fixed64 PACKETS = 8;
  if (this->_internal_packets() != 0) {
    total_size += 1 + 8;
  }

  // uint32 PROTOCOL = 5;
  if (this->_internal_protocol() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_protocol());
  }

  // uint32 TCP_FLAGS = 12;
  if (this->_internal_tcp_flags() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_tcp_flags());
  }

  // fixed64 PACKETS_REV = 9;
  if (this->_internal_packets_rev() != 0) {
    total_size += 1 + 8;
  }

  // fixed64 TIME_FIRST = 10;
  if (this->_internal_time_first() != 0) {
    total_size += 1 + 8;
  }

  // fixed64 TIME_LAST = 11;
  if (this->_internal_time_last() != 0) {
    total_size += 1 + 8;
  }

  // uint32 TCP_FLAGS_REV = 13;
  if (this->_internal_tcp_flags_rev() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_tcp_flags_rev());
  }

  // uint32 TTL = 14;
  if (this->_internal_ttl() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_ttl());
  }

  // uint32 TTL_REV = 15;
  if (this->_internal_ttl_rev() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_ttl_rev());
  }

  // uint32 FLOW_END_REASON = 16;
  if (this->_internal_flow_end_reason() != 0) {
    total_size += 2 +
      ::_pbi::WireFormatLite::UInt32Size(
        this->_internal_flow_end_reason());
  }

  // uint32 DNS_ANSWERS = 20;
  if (this->_internal_dns_answers() != 0) {
    total_size += 2 +
      ::_pbi::WireFormatLite::UInt32Size(
        this->_internal_dns_answers());
  }

  // uint32 DNS_ID = 21;
  if (this->_internal_dns_id() != 0) {
    total_size += 2 +
      ::_pbi::WireFormatLite::UInt32Size(
        this->_internal_dns_id());
  }

  // uint32 DNS_Q_TYPE = 22;
  if (this->_internal_dns_q_type() != 0) {
    total_size += 2 +
      ::_pbi::WireFormatLite::UInt32Size(
        this->_internal_dns_q_type());
  }

  // uint32 DNS_RR_RLENGTH = 23;
  if (this->_internal_dns_rr_rlength() != 0) {
    total_size += 2 +
      ::_pbi::WireFormatLite::UInt32Size(
        this->_internal_dns_rr_rlength());
  }

  // uint32 DNS_DO = 24;
  if (this->_internal_dns_do() != 0) {
    total_size += 2 +
      ::_pbi::WireFormatLite::UInt32Size(
        this->_internal_dns_do());
  }

  // uint32 DNS_RCODE = 25;
  if (this->_internal_dns_rcode() != 0) {
    total_size += 2 +
      ::_pbi::WireFormatLite::UInt32Size(
        this->_internal_dns_rcode());
  }

  // uint32 FME_TLS_SERVER_VERSION = 30;
  if (this->_internal_fme_tls_server_version() != 0) {
    total_size += 2 +
      ::_pbi::WireFormatLite::UInt32Size(
        this->_internal_fme_tls_server_version());
  }

  // uint32 HTTP_RESPONSE_STATUS_CODE = 40;
  if (this->_internal_http_response_status_code() != 0) {
    total_size += 2 +
      ::_pbi::WireFormatLite::UInt32Size(
        this->_internal_http_response_status_code());
  }

  // uint64 FLOW_ID = 50;
  if (this->_internal_flow_id() != 0) {
    total_size += 2 +
      ::_pbi::WireFormatLite::UInt64Size(
        this->_internal_flow_id());
  }

  // uint64 FLOW_COUNT = 51;
  if (this->_internal_flow_count() != 0) {
    total_size += 2 +
      ::_pbi::WireFormatLite::UInt64Size(
        this->_internal_flow_count());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData FlowRecord::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    FlowRecord::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*FlowRecord::GetClassData() const { return &_class_data_; }


void FlowRecord::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<FlowRecord*>(&to_msg);
  auto& from = static_cast<const FlowRecord&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ipfix.FlowRecord)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_src_ip().empty()) {
    _this->_internal_set_src_ip(from._internal_src_ip());
  }
  if (!from._internal_dst_ip().empty()) {
    _this->_internal_set_dst_ip(from._internal_dst_ip());
  }
  if (!from._internal_dns_q_name().empty()) {
    _this->_internal_set_dns_q_name(from._internal_dns_q_name());
  }
  if (!from._internal_tls_sni().empty()) {
    _this->_internal_set_tls_sni(from._internal_tls_sni());
  }
  if (!from._internal_http_request_agent().empty()) {
    _this->_internal_set_http_request_agent(from._internal_http_request_agent());
  }
  if (!from._internal_http_request_host().empty()) {
    _this->_internal_set_http_request_host(from._internal_http_request_host());
  }
  if (!from._internal_http_request_referer().empty()) {
    _this->_internal_set_http_request_referer(from._internal_http_request_referer());
  }
  if (!from._internal_http_request_url().empty()) {
    _this->_internal_set_http_request_url(from._internal_http_request_url());
  }
  if (!from._internal_http_response_content_type().empty()) {
    _this->_internal_set_http_response_content_type(from._internal_http_response_content_type());
  }
  if (from._internal_src_port() != 0) {
    _this->_internal_set_src_port(from._internal_src_port());
  }
  if (from._internal_dst_port() != 0) {
    _this->_internal_set_dst_port(from._internal_dst_port());
  }
  if (from._internal_bytes() != 0) {
    _this->_internal_set_bytes(from._internal_bytes());
  }
  if (from._internal_bytes_rev() != 0) {
    _this->_internal_set_bytes_rev(from._internal_bytes_rev());
  }
  if (from._internal_packets() != 0) {
    _this->_internal_set_packets(from._internal_packets());
  }
  if (from._internal_protocol() != 0) {
    _this->_internal_set_protocol(from._internal_protocol());
  }
  if (from._internal_tcp_flags() != 0) {
    _this->_internal_set_tcp_flags(from._internal_tcp_flags());
  }
  if (from._internal_packets_rev() != 0) {
    _this->_internal_set_packets_rev(from._internal_packets_rev());
  }
  if (from._internal_time_first() != 0) {
    _this->_internal_set_time_first(from._internal_time_first());
  }
  if (from._internal_time_last() != 0) {
    _this->_internal_set_time_last(from._internal_time_last());
  }
  if (from._internal_tcp_flags_rev() != 0) {
    _this->_internal_set_tcp_flags_rev(from._internal_tcp_flags_rev());
  }
  if (from._internal_ttl() != 0) {
    _this->_internal_set_ttl(from._internal_ttl());
  }
  if (from._internal_ttl_rev() != 0) {
    _this->_internal_set_ttl_rev(from._internal_ttl_rev());
  }
  if (from._internal_flow_end_reason() != 0) {
    _this->_internal_set_flow_end_reason(from._internal_flow_end_reason());
  }
  if (from._internal_dns_answers() != 0) {
    _this->_internal_set_dns_answers(from._internal_dns_answers());
  }
  if (from._internal_dns_id() != 0) {
    _this->_internal_set_dns_id(from._internal_dns_id());
  }
  if (from._internal_dns_q_type() != 0) {
    _this->_internal_set_dns_q_type(from._internal_dns_q_type());
  }
  if (from._internal_dns_rr_rlength() != 0) {
    _this->_internal_set_dns_rr_rlength(from._internal_dns_rr_rlength());
  }
  if (from._internal_dns_do() != 0) {
    _this->_internal_set_dns_do(from._internal_dns_do());
  }
  if (from._internal_dns_rcode() != 0) {
    _this->_internal_set_dns_rcode(from._internal_dns_rcode());
  }
  if (from._internal_fme_tls_server_version() != 0) {
    _this->_internal_set_fme_tls_server_version(from._internal_fme_tls_server_version());
  }
  if (from._internal_http_response_status_code() != 0) {
    _this->_internal_set_http_response_status_code(from._internal_http_response_status_code());
  }
  if (from._internal_flow_id() != 0) {
    _this->_internal_set_flow_id(from._internal_flow_id());
  }
  if (from._internal_flow_count() != 0) {
    _this->_internal_set_flow_count(from._internal_flow_count());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void FlowRecord::CopyFrom(const FlowRecord& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ipfix.FlowRecord)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FlowRecord::IsInitialized() const {
  return true;
}

void FlowRecord::InternalSwap(FlowRecord* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.src_ip_, lhs_arena,
      &other->_impl_.src_ip_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.dst_ip_, lhs_arena,
      &other->_impl_.dst_ip_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.dns_q_name_, lhs_arena,
      &other->_impl_.dns_q_name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.tls_sni_, lhs_arena,
      &other->_impl_.tls_sni_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.http_request_agent_, lhs_arena,
      &other->_impl_.http_request_agent_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.http_request_host_, lhs_arena,
      &other->_impl_.http_request_host_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.http_request_referer_, lhs_arena,
      &other->_impl_.http_request_referer_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.http_request_url_, lhs_arena,
      &other->_impl_.http_request_url_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.http_response_content_type_, lhs_arena,
      &other->_impl_.http_response_content_type_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(FlowRecord, _impl_.flow_count_)
      + sizeof(FlowRecord::_impl_.flow_count_)
      - PROTOBUF_FIELD_OFFSET(FlowRecord, _impl_.src_port_)>(
          reinterpret_cast<char*>(&_impl_.src_port_),
          reinterpret_cast<char*>(&other->_impl_.src_port_));
}

::PROTOBUF_NAMESPACE_ID::Metadata FlowRecord::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_schema_getter, &descriptor_table_schema_once,
      file_level_metadata_schema[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace ipfix
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::ipfix::FlowRecord*
Arena::CreateMaybeMessage< ::ipfix::FlowRecord >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ipfix::FlowRecord >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
