# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x06schema\x12\x05ipfix\"\xc6\x05\n\nFlowRecord\x12\x0e\n\x06SRC_IP\x18\x01 \x01(\x0c\x12\x0e\n\x06\x44ST_IP\x18\x02 \x01(\x0c\x12\x10\n\x08SRC_PORT\x18\x03 \x01(\r\x12\x10\n\x08\x44ST_PORT\x18\x04 \x01(\r\x12\x10\n\x08PROTOCOL\x18\x05 \x01(\r\x12\r\n\x05\x42YTES\x18\x06 \x01(\x06\x12\x11\n\tBYTES_REV\x18\x07 \x01(\x06\x12\x0f\n\x07PACKETS\x18\x08 \x01(\x06\x12\x13\n\x0bPACKETS_REV\x18\t \x01(\x06\x12\x12\n\nTIME_FIRST\x18\n \x01(\x06\x12\x11\n\tTIME_LAST\x18\x0b \x01(\x06\x12\x11\n\tTCP_FLAGS\x18\x0c \x01(\r\x12\x15\n\rTCP_FLAGS_REV\x18\r \x01(\r\x12\x0b\n\x03TTL\x18\x0e \x01(\r\x12\x0f\n\x07TTL_REV\x18\x0f \x01(\r\x12\x17\n\x0f\x46LOW_END_REASON\x18\x10 \x01(\r\x12\x13\n\x0b\x44NS_ANSWERS\x18\x14 \x01(\r\x12\x0e\n\x06\x44NS_ID\x18\x15 \x01(\r\x12\x12\n\nDNS_Q_TYPE\x18\x16 \x01(\r\x12\x16\n\x0e\x44NS_RR_RLENGTH\x18\x17 \x01(\r\x12\x0e\n\x06\x44NS_DO\x18\x18 \x01(\r\x12\x11\n\tDNS_RCODE\x18\x19 \x01(\r\x12\x12\n\nDNS_Q_NAME\x18\x1a \x01(\x0c\x12\x1e\n\x16\x46ME_TLS_SERVER_VERSION\x18\x1e \x01(\r\x12\x0f\n\x07TLS_SNI\x18\x1f \x01(\t\x12!\n\x19HTTP_RESPONSE_STATUS_CODE\x18( \x01(\r\x12\x1a\n\x12HTTP_REQUEST_AGENT\x18) \x01(\t\x12\x19\n\x11HTTP_REQUEST_HOST\x18* \x01(\t\x12\x1c\n\x14HTTP_REQUEST_REFERER\x18+ \x01(\t\x12\x18\n\x10HTTP_REQUEST_URL\x18, \x01(\t\x12\"\n\x1aHTTP_RESPONSE_CONTENT_TYPE\x18- \x01(\t\x12\x0f\n\x07\x46LOW_ID\x18\x32 \x01(\x04\x12\x12\n\nFLOW_COUNT\x18\x33 \x01(\x04\x42\x02H\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001'
  _FLOWRECORD._serialized_start=18
  _FLOWRECORD._serialized_end=728
# @@protoc_insertion_point(module_scope)
